---
title: "PRJCT"
author: 
- name: "Mickaël Canouil, *Ph.D.*"
  affiliation: "Université de Lille, CNRS, Institut Pasteur de Lille, UMR 8199 - EGID, F-59000, Lille, France."
  email: "mickael.canouil@cnrs.fr"
date: '`r format(Sys.time(), "%B %d, %Y")`'
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
params:
  script_name: NULL
  project_directory: "~/PRJCT"
  working_directory: "~/PRJCT"
  show_code: FALSE
  n_cores: !r parallel::detectCores()
  dpi: 120
  gg_fontsize: 12
output:
  bookdown::html_document2:
    theme: simplex
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
    fig_width: 6.3
    fig_height: 4.7
    number_sections: true
    self_contained: true
    mathjax: default
    df_print: kable
---

```{r setup, include = FALSE}
options(stringsAsFactors = FALSE)

### Load packages and functions
library(parallel)
library(tidyverse)
library(scales)
library(grid)

pretty_kable <- function (
  data, 
  font_size = 12, 
  format_args = list(scientific = -1, digits = 3, big.mark = ","), 
  col.names = NA,
  full_width = FALSE,
  format = "html",
  ...
) {
  output <- knitr::kable(
    x = data, 
    format.args = format_args, 
    col.names = col.names,
    ...
  )
  kableExtra::kable_styling(
    kable_input = output,
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = full_width,
    position = "center",
    font_size = font_size
  )
}

devtools::source_url("https://github.com/mcanouil/DEV/raw/master/R/theme_black.R")

### Set knitr rmarkdown chunk options
output_directory <- paste(
  params[["working_directory"]], 
  params[["script_name"]], 
  sep = "/"
)
dir.create(
  path = paste0(output_directory, "/cache/"), 
  recursive = TRUE, 
  showWarnings = FALSE, 
  mode = "0777"
)
knitr::opts_chunk$set(
  results = "asis",
  size = "small",
  include = TRUE,
  echo = params[["show_code"]],
  warning = params[["show_code"]],
  message = params[["show_code"]],
  dpi = params[["dpi"]],
  tidy = FALSE,
  crop = TRUE,
  autodep = TRUE,
  fig.align = "center",
  fig.pos = "!H",
  cache = params[["cache"]],
  cache.path = paste0(output_directory, "/cache/"),
  fig.path = paste0(output_directory, "/cache/")
)


### Define theme
theme_set(theme_light(base_size = params[["gg_fontsize"]]))
```

# Summary


# R session information

```{r session_info, results = "markup"}
options("width" = 110)
sessioninfo::session_info()
```
